AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 36

Metrics/BlockLength:
  Exclude:
    - spec/*.rb

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 26

Security/YAMLLoad:
  Exclude:
    - lib/yamllint/linter.rb
